### ISSUE TITLE
Store frame time, not frame rate

### ISSUE THREAD

**Issue by alice-i-cecile** [aevyrie/bevy_framepace#11]
When used, we're taking the inverse every frame (and converting it to an f32).

Instead, store an `f32` frame time in the `FrameRateLimit` resource (see #10) and use that directly to save on wasted work and reduce complexity.

Provider helper methods to allow users to specify the settings with either frame rates or frame times.

**Comment by aevyrie** [comment]
Yeah, I waffled on this a bit, I think you're right that this is a better approach.
