### ISSUE TITLE
Unnecessary features in Cargo.toml

### ISSUE THREAD

**Issue by Nhlest** [aevyrie/bevy_framepace#21]
Cargo.toml lists `render` as a required feature which causes bevy to be built with a lot of unnecessary features like `bevy_pbr` and `beby_gltf`. This is unnecessary and can be simplified to only `bevy_render`.

**Comment by Nhlest** [comment]
I would have submitted a PR but i am not sure how to approach that with current HEAD pointing to bevy/main branch. Any way to retroactively add this to the 0.8 version of this plugin?

**Comment by aevyrie** [comment]
You can PR to main, and I'll backport to the crates.io version. You can also PR against `release` which points to the bevy crates release.
