### ISSUE TITLE
WASM: Limiter::from_framerate(30.0) not working

### ISSUE THREAD

**Issue by Nickan** [aevyrie/bevy_framepace#38]
It works on native build, but running `cargo make web` for wasm doesn't limit the framerate. Thanks.

Here is my repo test: https://github.com/Nickan/bevytest/tree/BevyFramepace

Edit: Provide github repo link

**Comment by aevyrie** [comment]
Framelimiting/pacing is disabled on WASM so as not to compete with the browser's framepacer. Enabling pacing/limiting on WASM builds does not work anyway. I have been unable to get it to work, in part because precising sleep and timing in WASM are not trivial.
